version: "3.8"

services:
  salompoq:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - ./bot_state.json:/app/bot_state.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
